services:
  db:
    build: ./Database/
    restart: unless-stopped
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  maquina:
    build: ./Linux/
    ports:
    - "127.0.0.1:8080:8080"
    depends_on:
      db:
        condition: service_healthy