services:
  db:
    build: ./Postgres/
    image: postgres_airflow
    container_name: postgres_para_airflow
    restart: unless-stopped
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  maquina:
    build: ./Linux/
    image: linux_airflow
    container_name: ubuntu_para_airflow
    restart: always
    ports:
    - "127.0.0.1:8080:8080"
    depends_on:
      db:
        condition: service_healthy