##Puxando Imagem
FROM postgres:16.6

#Definindo Variáveis de Ambiente 

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=airflow_db
ENV POSTGRES_ROOT_PASSWORD=airflow

##COPY ./init.sql /docker-entrypoint-initdb.d/init.sql

EXPOSE 5432